# Generated by Django 2.1.4 on 2018-12-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lecture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='name',
            new_name='title',
        ),
    ]
