# Generated by Django 2.1.4 on 2018-12-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181225_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='undertitle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
