# Generated by Django 2.1.4 on 2018-12-25 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lecture_undertitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tittel'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='undertitle',
            field=models.CharField(max_length=200, null=True, verbose_name='Undertittel'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='url',
            field=models.CharField(max_length=200, verbose_name='Url'),
        ),
    ]
