# Generated by Django 2.1.4 on 2018-12-25 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181226_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
