# Generated by Django 2.1.4 on 2018-12-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181226_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Navn')),
                ('color', models.CharField(max_length=20, verbose_name='Farge')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='tags',
            field=models.ManyToManyField(related_name='lectures', to='app.Tag'),
        ),
    ]
