# Generated by Django 2.1.4 on 2018-12-26 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181226_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='color',
            new_name='label',
        ),
    ]
