# Generated by Django 2.1.4 on 2018-12-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181226_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='label',
            field=models.CharField(max_length=20, verbose_name='Bootstrap-klasse'),
        ),
    ]
