# Generated by Django 2.1.4 on 2018-12-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181226_0241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-label']},
        ),
        migrations.AddField(
            model_name='lecture',
            name='target_audience',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Målgruppe'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='lectures', to='app.Tag'),
        ),
    ]
