# Generated by Django 2.1.4 on 2018-12-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181226_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='tasks',
            field=models.IntegerField(blank=True, null=True, verbose_name='Oppgaver'),
        ),
    ]
