# Generated by Django 2.1.4 on 2018-12-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_lecture_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='url',
            field=models.CharField(help_text='Til Google-docs presentasjon', max_length=200, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='label',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], max_length=20, verbose_name='Bootstrap-klasse'),
        ),
    ]
